### ISSUE TITLE
Building from source triggers a bug in rustc

### ISSUE THREAD

**Issue by johanneskoester** [conda-forge/rust-feedstock#3]
We cannot currently build from source, because this leads to a bug in rustc, see rust-lang/rust#43311.

**Comment by bollwyvl** [comment]
Hey, folks. I wonder if this is worth revisiting in the conda-build 3 era?

I tried in earnest to get this going for a windows package over on https://github.com/conda-forge/staged-recipes/pull/5789#issuecomment-387910799 but ended up having to fall back to the legacy compiler setup. I have the sneaking suspicion that it is compiler related, and bringing this into the cb3 fold might help.

**Comment by pkgw** [comment]
Also, FWIW, there should be a new version of Rust coming out today, so it's not a bad time to experiment with the build process since we'll be exercising it anyway.

**Comment by bollwyvl** [comment]
I'm very much a Rust noob, and really just want to test some websites with
a predictable version of geckodriver instead of maintaining x curl/tar
scripts on y platforms.

My initial pr was just grabbing GitHub binaries, but these didn't include
licenses (wontfix) and various other things. So I tried the build and we
were mostly happy, but the new compilers don't work, plus some fighting
with vs200x that was unproductive.

Going back to the legacy build chain "works" but I am blessed with not
having Windows to test with, and since you need a whole Firefox to really
try it, it seems aggressive to do in ci at this point.

The most common error with the new compilers revolves around external bz2
functions, but on *nix that doesn't even show up in the link list, so it
might be statically linking? However it does link to some things.

It could be I just need some Rustflags, but there aren't any other rust
packages built by cf on Windows yet for me to crib from. Any insight
welcome!

As to building rust: I don't know enough to have an opinion... unless it
fixes my build!

**Comment by pkgw** [comment]
@bollwyvl Hmmm. Based on your `geckodriver` error messages I am not sure if the way that Rust is built and packaged is the sole cause of the problems, but it's definitely hard to say without some investigation. If you have spare time and bandwidth, Microsoft creates [free Windows VM images](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) that can be used to investigate Windows build issues even if you don't have a dedicated machine.

**Comment by jakirkham** [comment]
> Microsoft creates [free Windows VM images](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) that can be used to investigate Windows build issues even if you don't have a dedicated machine.

Nice find, @pkgw! Would you be willing to add a PR to the webpage repo documenting this resource?

**Comment by pkgw** [comment]
I am going to close this — we have Rust on all three platforms now, and I don't believe that building it from source buys us anything except burning more CI CPU cycles.
