### ISSUE TITLE
Patch to disable cargo downloads during conda-build

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/rust-feedstock#6]
With `setuptools`, we patch it to [disallow downloads while `conda-build` is running]( https://github.com/conda-forge/setuptools-feedstock/blob/3789960750ef0c5e420bbe56aa8c826c47da2dd4/recipe/nodownload.patch ). This allows us to ensure maintainers explicitly list all dependencies in their recipes. Is there a similar strategy that we could apply to `cargo`?

**Comment by pkgw** [comment]
I am definitely not a fan of build procedures that download files from the internet, but `cargo` and `setuptools` operate in fairly different ways. The dependencies encoded by Cargo are much finer-grained than Python package dependencies, and they end up being statically compiled into the build output so that the resulting program does not actually depend on them at runtime. In other words, I don't think the "explicitly list all dependencies in their recipes" factor is desirable here since we don't want to have hundreds of packages for little utility Rust crates that never actually need to stand alone.

I *don't* have any good idea of how to set things up such that we could build Rust packages on an internet-disconnected box, which kind of annoys me. But Conda is in the same boat.

**Comment by johanneskoester** [comment]
Yes, I agree. With rust, you typically want a static binary including all (crate-level) dependencies.
